color = input("Enter a color : ")
Plural_noun = input("Enter a plural noun : ")
celebrity = input("Enter a name of celebrity you like: ")
print("roses are " + color + ".")
print(Plural_noun+ " are blue")
print("I love " + celebrity + ".")
